---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: O Astra é um serviço de gerenciamento de ciclo de vida de dados de aplicações Kubernetes que simplifica as operações de aplicações com estado monitorado. Proteja, faça backup e migre workloads do Kubernetes com facilidade e crie clones de aplicações em funcionamento instantaneamente. 
---
= Saiba mais sobre o Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O Astra Control é uma solução de gerenciamento do ciclo de vida de dados de aplicativos Kubernetes que simplifica as operações para aplicativos com estado e ajuda você a armazenar, proteger e mover suas cargas de trabalho do Kubernetes entre ambientes híbridos.



== Recursos

O Astra Control oferece funcionalidades essenciais para o gerenciamento do ciclo de vida dos dados da aplicação Kubernetes:

*Loja*:

* Provisionamento de storage dinâmico para workloads em contêineres
* Criptografia em trânsito de dados do contêiner para volumes persistentes
* Replicação entre regiões, entre zonas


* Proteger*:

* Detecção automatizada e proteção com reconhecimento de aplicações de toda uma aplicação e seus dados
* Recuperação instantânea de um aplicativo a partir de qualquer versão de snapshot com base nas necessidades da sua organização
* Failover rápido em zonas, regiões e fornecedores de nuvem


*Mover*:

* Mobilidade de dados e aplicações entre clusters do Kubernetes e nuvens
* Clones instantâneos de aplicações e dados inteiros
* Migração de aplicativos com um clique por meio de IU e API consistentes da Web




== Arquitetura

A arquitetura do Astra Control permite que a TI forneça recursos avançados de gerenciamento de dados que aprimoram o recurso e a disponibilidade das aplicações Kubernetes, simplifica o gerenciamento, a proteção e a movimentação de workloads em contêineres entre nuvens públicas e ambientes locais, além de fornecer recursos de automação por meio de sua API REST e SDK, permitindo acesso programático para integração aprimorada com workflows existentes.

O Astra Control é nativo em Kubernetes, permitindo workflows de proteção de dados que utilizam recursos personalizados e, ao mesmo tempo, permanecem compatíveis com a API e o SDK existentes. A proteção de dados nativa do Kubernetes oferece vantagens significativas. Ao integrar de forma otimizada às APIs e aos recursos do Kubernetes, a proteção de dados pode se tornar uma parte inerente do ciclo de vida do aplicativo por meio das ferramentas existentes de CI/CD e/ou GitOps de uma organização.

O Astra Control foi desenvolvido com base em quatro componentes complementares:

* *Astra Control*: O Astra Control é o serviço de gerenciamento centralizado para todos os clusters gerenciados, fornecendo cargas de trabalho orquestradas para proteção e mobilidade de aplicativos locais, bem como os seguintes recursos:
+
** Visão combinada de vários clusters
** Proteção de fluxos de trabalho orquestrados
** Visualização e seleção granular de recursos


* *Astra Connector*: O Astra Connector combina com o Astra Control para fornecer uma conexão segura a cada cluster gerenciado, oferecendo execução local de operações agendadas independentemente do status da conexão, bem como as seguintes funcionalidades:
+
** Execução local de operações agendadas independentemente do status da conexão
** Operações locais que distribuem e otimizam o uso de recursos do sistema do Astra entre clusters
** Instalação local que permite o menor acesso de privilégios ao cluster para maior segurança


* *Astra Control Provisioner*: O Astra Control Provisioner oferece a funcionalidade de provisionamento de CSI básico e recursos avançados de gerenciamento de storage para configuração adicional de segurança e recuperação de desastres, bem como os seguintes recursos:
+
** Provisionamento de storage dinâmico para workloads em contêineres
** Gerenciamento avançado de storage:
+
*** Criptografia em trânsito de dados do contêiner para o PV
*** Funcionalidade de nuvem SnapMirror com replicação entre regiões e entre zonas




* *Recursos personalizados do Astra*: Os recursos personalizados usados em cada cluster fornecem uma abordagem nativa do Kubernetes para executar operações localmente, simplificando a integração com outras ferramentas e automação compatíveis com o Kubernetes, além de fornecer os seguintes recursos:
+
** Workflows de automação e integração direta de ferramentas de ecossistema
** Primitivas de nível inferior que permitem fluxos de trabalho personalizados






== Modelos de implantação

O Astra Control está disponível em um único modelo de implantação.

*Astra Control Center*: Software autogerenciado que oferece gerenciamento de dados com reconhecimento de aplicações dos clusters Kubernetes executados em seu ambiente local. O Astra Control Center também pode ser instalado em vários ambientes de fornecedor de nuvem com um back-end de storage da NetApp Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/astra-control-center/["Documentação do Astra Control Center"^]

[cols="1h,2d"]
|===
|  | Astra Control Center 


| Como é oferecido? | Como software que você pode baixar, instalar e gerenciar 


| Onde está hospedado? | No seu próprio cluster Kubernetes 


| Como é atualizado? | Você gerencia quaisquer atualizações 


| Quais são as distribuições compatíveis do Kubernetes?  a| 
* Serviço Kubernetes do Azure no Azure Stack HCI
* Google Anthos
* Kubernetes (upstream)
* Rancher Kubernetes Engine (RKE)
* Red Hat OpenShift Container Platform




| Quais são os backends de armazenamento suportados?  a| 
* Sistemas NetApp ONTAP AFF e FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Para mais informações

* https://docs.netapp.com/us-en/astra-control-center/["Documentação do Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentação do Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["API Astra Control"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentação do Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentação do ONTAP"^]

